"""Real LEGO parts and colours, taken from the Rebrickable catalogue.

Every part number and colour ID below appears in Rebrickable's public catalogue
dumps (https://rebrickable.com/downloads/). Colours are filtered to solid,
currently-produced ones — no transparent, metallic or long-discontinued shades,
so a generated parts list is something you can actually buy.

The tables below are hand-picked: they are the parts the generator actually
places, ordered for the greedy partitioner. The much larger shape library it can
draw on is measured rather than written — see lego_shapes.py and the generator
that produces it, scripts/build_shape_library.py.
"""

from typing import NamedTuple

from app.services import lego_shapes as shapes


BRICK_LDU = 24  # a brick course
PLATE_LDU = 8  # a plate, and a tile: a third of a brick


class Plate(NamedTuple):
    part_num: str
    name: str
    width: int  # studs along x
    length: int  # studs along y
    # How tall the part is. Everything used to be a brick, so this could be
    # implied; tiles and plates are a third the height, and a caller that assumes
    # otherwise stacks the next course 16 LDU into thin air.
    height: int = BRICK_LDU

    @property
    def area(self) -> int:
        return self.width * self.length


# Plates rather than bricks: a plate is a third the height of a brick, so a
# stepped relief built from plates has three times the depth resolution for the
# same physical thickness.
PLATES: list[Plate] = [
    Plate("3034", "Plate 2 x 8", 2, 8, PLATE_LDU),
    Plate("3795", "Plate 2 x 6", 2, 6, PLATE_LDU),
    Plate("3460", "Plate 1 x 8", 1, 8, PLATE_LDU),
    Plate("3020", "Plate 2 x 4", 2, 4, PLATE_LDU),
    Plate("3666", "Plate 1 x 6", 1, 6, PLATE_LDU),
    Plate("3021", "Plate 2 x 3", 2, 3, PLATE_LDU),
    Plate("3022", "Plate 2 x 2", 2, 2, PLATE_LDU),
    Plate("3710", "Plate 1 x 4", 1, 4, PLATE_LDU),
    Plate("3623", "Plate 1 x 3", 1, 3, PLATE_LDU),
    Plate("3023", "Plate 1 x 2", 1, 2, PLATE_LDU),
    Plate("3024", "Plate 1 x 1", 1, 1, PLATE_LDU),
]

# Largest first — the greedy partitioner depends on this ordering.
PLATES_BY_AREA = sorted(PLATES, key=lambda p: -p.area)

# Bricks, for the standing build. A wall is courses of bricks; plates would give a
# finer vertical step but no wall is built from plates — they have no grip on their
# own and a wall of them shears apart. `width` runs along the facade, `length` into
# it, which is the same convention as the plate table above.
BRICKS: list[Plate] = [
    Plate("3006", "Brick 2 x 10", 10, 2),
    Plate("3007", "Brick 2 x 8", 8, 2),
    Plate("3008", "Brick 1 x 8", 8, 1),
    Plate("3009", "Brick 1 x 6", 6, 1),
    Plate("3001", "Brick 2 x 4", 4, 2),
    Plate("3010", "Brick 1 x 4", 4, 1),
    Plate("3002", "Brick 2 x 3", 3, 2),
    Plate("3622", "Brick 1 x 3", 3, 1),
    Plate("3003", "Brick 2 x 2", 2, 2),
    Plate("3004", "Brick 1 x 2", 2, 1),
    Plate("3005", "Brick 1 x 1", 1, 1),
]

BRICKS_BY_AREA = sorted(BRICKS, key=lambda p: -p.area)

# Bricks one stud deep, for the facade skin — the visible face has to be exactly
# one stud thick so a single brick never spans two different facade colours.
SKIN_BRICKS = sorted((b for b in BRICKS if b.length == 1), key=lambda p: -p.width)

# Tiles — a plate with no studs on top.
#
# What they buy is the roofline. Every step in a wall's silhouette currently ends
# in a row of bare studs pointing at the sky, which is the single strongest visual
# cue that you are looking at a toy rather than a building. Capping those steps
# with tiles reads as coping stone, and it is what a builder would actually do.
TILES: list[Plate] = [
    Plate("4162", "Tile 1 x 8", 8, 1, PLATE_LDU),
    Plate("6636", "Tile 1 x 6", 6, 1, PLATE_LDU),
    Plate("2431", "Tile 1 x 4", 4, 1, PLATE_LDU),
    Plate("63864", "Tile 1 x 3", 3, 1, PLATE_LDU),
    Plate("3069b", "Tile 1 x 2", 2, 1, PLATE_LDU),
    Plate("3070b", "Tile 1 x 1", 1, 1, PLATE_LDU),
]

TILES_BY_AREA = sorted(TILES, key=lambda p: -p.area)

# ---------------------------------------------------------------------------
# The shape library: 230 parts, in fourteen families, held in reserve.
#
# These are not written here. lego_shapes.py is generated by
# scripts/build_shape_library.py, which measures every part out of the official
# LDraw geometry and counts how many released sets it appears in. That is the
# point: the first version of this section was four short tables written from
# memory, and there was no way to know whether "Slope 45 2 x 1" descends along X
# or Z — which is precisely the number a placement rule needs and the one thing a
# part's name never tells you. It is measured now (`slope_axis`, `slope_dir`),
# for all thirty-five slopes at once, and nobody has to eyeball a render to check.
#
# Placement rules are still to be written; the parts and their geometry are ready.
# ---------------------------------------------------------------------------

SLOPES = shapes.family("slope")
SLOPES_INVERTED = shapes.family("slope_inverted")
ARCHES = shapes.family("arch")
CURVED = shapes.family("curved")
ROUND_BRICKS = shapes.family("round_brick")
CONES = shapes.family("cone")
DISHES = shapes.family("dish")
PANELS = shapes.family("panel")
WEDGE_PLATES = shapes.family("wedge_plate")

BASEPLATES = [
    ("3811", "Baseplate 32 x 32", 32, 32),
    ("3867", "Baseplate 16 x 16", 16, 16),
]

# Footprint by part number, for laying them out. Kept beside the table it derives
# from so the two cannot drift.
BASEPLATE_SIZE: dict[str, tuple[int, int]] = {p: (w, h) for p, _, w, h in BASEPLATES}


class Colour(NamedTuple):
    colour_id: int  # Rebrickable colour ID
    name: str  # official LEGO / BrickLink colour name
    rgb: tuple[int, int, int]

    @property
    def hex(self) -> str:
        """The colour as `#RRGGBB`, for clients that draw a swatch.

        Names alone are not enough on the wire: a client that keeps its own
        name→hex table silently falls back to grey the moment this catalogue
        gains a colour, and the drift is invisible until someone looks at a
        rendered palette. Shipping the hex from here keeps one source of truth.
        """
        return "#{:02X}{:02X}{:02X}".format(*self.rgb)


# Solid colours in current production, ordered by how much of the catalogue they
# cover. Filter used: is_trans=False, last-seen year >= 2020, >800 known parts,
# minus metallics/chrome/glitter (expensive, and they photograph badly) and the
# pre-2004 greys 7/8 that LEGO replaced with the bluish greys.
#
# The pastels near the bottom of the list carry no weight in the catalogue but
# are what make a photo readable — Bright Light Blue is the sky in most outdoor
# shots, and without it skies quantise to grey-green.
COLOURS: list[Colour] = [
    Colour(0, "Black", (0x05, 0x13, 0x1D)),
    Colour(15, "White", (0xFF, 0xFF, 0xFF)),
    Colour(71, "Light Bluish Gray", (0xA0, 0xA5, 0xA9)),
    Colour(72, "Dark Bluish Gray", (0x6C, 0x6E, 0x68)),
    Colour(4, "Red", (0xC9, 0x1A, 0x09)),
    Colour(14, "Yellow", (0xF2, 0xCD, 0x37)),
    Colour(1, "Blue", (0x00, 0x55, 0xBF)),
    Colour(19, "Tan", (0xE4, 0xCD, 0x9E)),
    Colour(70, "Reddish Brown", (0x58, 0x2A, 0x12)),
    Colour(2, "Green", (0x23, 0x78, 0x41)),
    Colour(28, "Dark Tan", (0x95, 0x8A, 0x73)),
    Colour(25, "Orange", (0xFE, 0x8A, 0x18)),
    Colour(272, "Dark Blue", (0x0A, 0x34, 0x63)),
    Colour(320, "Dark Red", (0x72, 0x0E, 0x0F)),
    Colour(27, "Lime", (0xBB, 0xE9, 0x0B)),
    Colour(84, "Medium Nougat", (0xAA, 0x7D, 0x55)),
    Colour(191, "Bright Light Orange", (0xF8, 0xBB, 0x3D)),
    Colour(322, "Medium Azure", (0x36, 0xAE, 0xBF)),
    Colour(484, "Dark Orange", (0xA9, 0x55, 0x00)),
    Colour(10, "Bright Green", (0x4B, 0x9F, 0x4A)),
    Colour(288, "Dark Green", (0x18, 0x46, 0x32)),
    Colour(378, "Sand Green", (0xA0, 0xBC, 0xAC)),
    Colour(308, "Dark Brown", (0x35, 0x21, 0x00)),
    Colour(3, "Dark Turquoise", (0x00, 0x8F, 0x9B)),
    Colour(29, "Bright Pink", (0xE4, 0xAD, 0xC8)),
    Colour(85, "Dark Purple", (0x3F, 0x36, 0x91)),
    Colour(321, "Dark Azure", (0x07, 0x8B, 0xC9)),
    Colour(5, "Dark Pink", (0xC8, 0x70, 0xA0)),
    Colour(26, "Magenta", (0x92, 0x39, 0x78)),
    Colour(73, "Medium Blue", (0x5A, 0x93, 0xDB)),
    Colour(226, "Bright Light Yellow", (0xFF, 0xF0, 0x3A)),
    Colour(326, "Olive Green", (0x9B, 0x9A, 0x5A)),
    Colour(78, "Light Nougat", (0xF6, 0xD7, 0xB3)),
    Colour(323, "Light Aqua", (0xAD, 0xC3, 0xC0)),
    Colour(379, "Sand Blue", (0x60, 0x74, 0xA1)),
    Colour(30, "Medium Lavender", (0xAC, 0x78, 0xBA)),
    Colour(212, "Bright Light Blue", (0x9F, 0xC3, 0xE9)),
    Colour(31, "Lavender", (0xE1, 0xD5, 0xED)),
    Colour(1050, "Coral", (0xFF, 0x69, 0x8F)),
    Colour(158, "Yellowish Green", (0xDF, 0xEE, 0xA5)),
    Colour(1136, "Reddish Orange", (0xCA, 0x4C, 0x0B)),
    Colour(92, "Nougat", (0xD0, 0x91, 0x68)),
    Colour(1062, "Vibrant Yellow", (0xEB, 0xD8, 0x00)),
]

# Glazing.
#
# A window at this scale is not a window part. The catalogue's window frames are
# two courses tall and a fixed four studs wide, so placing one means finding an
# opening of exactly that size and hoping the building agrees; and the moment one
# lands half a course out, the whole wall around it has to shift. What LEGO's own
# Architecture sets do instead is simpler and looks better: ordinary brick shapes
# in a transparent colour. The geometry is unchanged, every size in the brick
# table is available, and the result reads as glass because it *is* glass.
#
# Trans-Brown first because it is smoked glass, which is what a window in a
# photograph almost always is — a dark opening, not a clear one. Trans-Clear reads
# as a hole in the wall from most angles.
GLAZING: list[Colour] = [
    Colour(40, "Trans-Brown", (0x63, 0x5F, 0x52)),
    Colour(47, "Trans-Clear", (0xFC, 0xFC, 0xFC)),
    Colour(41, "Trans-Light Blue", (0xAE, 0xEF, 0xEC)),
    Colour(33, "Trans-Dark Blue", (0x00, 0x20, 0xA0)),
]

# The one used unless a caller says otherwise.
DEFAULT_GLAZING_ID = 40

COLOURS_BY_ID = {c.colour_id: c for c in COLOURS + GLAZING}

# What the hidden support columns are built from. One cheap, ubiquitous colour
# beats matching the surface: nobody sees it, and it keeps the shopping list short.
FILL_COLOUR_ID = 71  # Light Bluish Gray


def nearest_colour(rgb: tuple[int, int, int]) -> Colour:
    """Snap an arbitrary RGB value to the closest colour LEGO actually sells.

    Uses the "redmean" weighted distance, which tracks human colour perception
    far better than plain Euclidean RGB while needing no colour-space conversion.
    """
    r, g, b = rgb
    best = COLOURS[0]
    best_dist = float("inf")
    for colour in COLOURS:
        cr, cg, cb = colour.rgb
        rmean = (r + cr) / 2
        dr, dg, db = r - cr, g - cg, b - cb
        dist = (
            (2 + rmean / 256) * dr * dr
            + 4 * dg * dg
            + (2 + (255 - rmean) / 256) * db * db
        )
        if dist < best_dist:
            best_dist = dist
            best = colour
    return best


def choose_baseplate(grid_w: int, grid_h: int) -> dict[str, object]:
    """Pick the baseplate arrangement that covers the build area."""
    for part_num, name, bw, bh in BASEPLATES:
        if grid_w <= bw and grid_h <= bh:
            return {"partId": part_num, "name": name, "quantity": 1}
    # Larger than a single 32x32 — tile them.
    part_num, name, bw, bh = BASEPLATES[0]
    across = -(-grid_w // bw)
    down = -(-grid_h // bh)
    return {"partId": part_num, "name": name, "quantity": across * down}
