"""Real LEGO parts and colours, taken from the Rebrickable catalogue.

Every part number and colour ID below appears in Rebrickable's public catalogue
dumps (https://rebrickable.com/downloads/). Colours are filtered to solid,
currently-produced ones — no transparent, metallic or long-discontinued shades,
so a generated parts list is something you can actually buy.

The tables below are hand-picked: they are the parts the generator actually
places, ordered for the greedy partitioner. The much larger shape library it can
draw on is measured rather than written — see lego_shapes.py and the generator
that produces it, scripts/build_shape_library.py.
"""

import re
from typing import Any, NamedTuple

from app.services import lego_shapes as shapes


BRICK_LDU = 24  # a brick course
PLATE_LDU = 8  # a plate, and a tile: a third of a brick


class Plate(NamedTuple):
    part_num: str
    name: str
    width: int  # studs along x
    length: int  # studs along y
    # How tall the part is. Everything used to be a brick, so this could be
    # implied; tiles and plates are a third the height, and a caller that assumes
    # otherwise stacks the next course 16 LDU into thin air.
    height: int = BRICK_LDU

    @property
    def area(self) -> int:
        return self.width * self.length


# The rectangular tables, taken from the measured shape library rather than
# written out here.
#
# They were hand-written, and the hand stopped at 2 x 10 for a brick and 2 x 8
# for a plate. That ceiling is most of why a finished model is 36% 1 x 1 bricks:
# the partitioner reaches for the largest part that fits, and the largest part
# it had was small. The library has Brick 16 x 8, Brick 24 x 12, Plate 16 x 16 —
# all measured, all real — and none of them were reachable.
#
# One part per footprint, the one that appears in the most sets, so the shopping
# list stays sourceable even though the table is now generated.


def _rectangles(family: str, height: int = BRICK_LDU) -> list[Plate]:
    """Every distinct footprint in a family, largest first."""
    best: dict[tuple[int, int], Any] = {}
    for shape in shapes.family(family):
        key = (shape.width, shape.depth)
        if key not in best or shape.sets > best[key].sets:
            best[key] = shape
    return sorted(
        (Plate(s.part_num, s.name, w, d, height) for (w, d), s in best.items()),
        key=lambda p: -p.area,
    )


# Plates rather than bricks under the model: a plate is a third the height of a
# brick, so a floor built from plates adds a third of a course rather than a
# whole one.
PLATES: list[Plate] = _rectangles("plate", PLATE_LDU)
PLATES_BY_AREA = PLATES

# Bricks, for the standing build. A wall is courses of bricks; plates would give a
# finer vertical step but no wall is built from plates — they have no grip on their
# own and a wall of them shears apart. `width` runs along the facade, `length` into
# it, which is the same convention as the plate table above.
BRICKS: list[Plate] = _rectangles("brick")
BRICKS_BY_AREA = BRICKS

# Bricks one stud deep, for the facade skin — the visible face has to be exactly
# one stud thick so a single brick never spans two different facade colours.
SKIN_BRICKS = sorted((b for b in BRICKS if b.length == 1), key=lambda p: -p.width)

# Tiles — a plate with no studs on top.
#
# What they buy is the roofline. Every step in a wall's silhouette currently ends
# in a row of bare studs pointing at the sky, which is the single strongest visual
# cue that you are looking at a toy rather than a building. Capping those steps
# with tiles reads as coping stone, and it is what a builder would actually do.
TILES: list[Plate] = _rectangles("tile", PLATE_LDU)
TILES_BY_AREA = TILES

# ---------------------------------------------------------------------------
# The shape library: 230 parts, in fourteen families, held in reserve.
#
# These are not written here. lego_shapes.py is generated by
# scripts/build_shape_library.py, which measures every part out of the official
# LDraw geometry and counts how many released sets it appears in. That is the
# point: the first version of this section was four short tables written from
# memory, and there was no way to know whether "Slope 45 2 x 1" descends along X
# or Z — which is precisely the number a placement rule needs and the one thing a
# part's name never tells you. It is measured now (`slope_axis`, `slope_dir`),
# for all thirty-five slopes at once, and nobody has to eyeball a render to check.
#
# Placement rules are still to be written; the parts and their geometry are ready.
# ---------------------------------------------------------------------------

class Panel(NamedTuple):
    """A wall one stud thick, standing a whole number of courses tall.

    The part that lets a facade stop being a stack of courses. A Panel 1 x 6 x 5
    is one piece where the brick-by-brick partitioner needs thirty, and it is
    what the walls of a real Architecture set are made of — the partitioner works
    a course at a time and so can never spend the vertical coherence a flat wall
    has, however flat it is.
    """

    part_num: str
    name: str
    width: int  # studs along the wall
    courses: int  # courses tall
    # Which way the finished face points in the part's own coordinates. Measured
    # — see lego_shapes — because it is not the same for every panel.
    wall_side: str

    @property
    def area(self) -> int:
        return self.width * self.courses


# Plain walls only. "Panel 1 x 4 x 5 with Arched Window" is a real part and a
# good one, but it is a window: putting it in the table the wall-filler reaches
# for would punch arched holes through a facade at random. Panels with openings
# want to be chosen for a reason, which is a different pass than this one.
#
# "Corner" is singular on purpose. A "Panel 1 x 1 x 1 Corner" turns a corner and
# does not belong here; "Panel 1 x 2 x 1 [Rounded Corners]" is a flat wall with
# its edges softened, and matching the word loosely dropped it along with the
# 1 x 4 x 1 — the two commonest thin walls in the library.
_PATTERNED = re.compile(r"Window|Arch|Divider|Corrugated|\bCorner\b")


def _panels() -> list[Panel]:
    """Every plain full-course panel footprint, largest first."""
    best: dict[tuple[int, int], Any] = {}
    for shape in shapes.family("panel"):
        courses = shape.height / BRICK_LDU
        if shape.depth != 1 or abs(courses - round(courses)) > 0.01:
            continue
        if shape.wall_side is None or _PATTERNED.search(shape.name):
            continue
        key = (shape.width, int(round(courses)))
        if key not in best or shape.sets > best[key].sets:
            best[key] = shape
    return sorted(
        (
            Panel(s.part_num, s.name, w, c, s.wall_side)
            for (w, c), s in best.items()
        ),
        key=lambda p: -p.area,
    )


PANEL_WALLS = _panels()


SLOPES = shapes.family("slope")
SLOPES_INVERTED = shapes.family("slope_inverted")
ARCHES = shapes.family("arch")
CURVED = shapes.family("curved")
ROUND_BRICKS = shapes.family("round_brick")
CONES = shapes.family("cone")
DISHES = shapes.family("dish")
PANELS = shapes.family("panel")
WEDGE_PLATES = shapes.family("wedge_plate")

BASEPLATES = [
    ("3811", "Baseplate 32 x 32", 32, 32),
    ("3867", "Baseplate 16 x 16", 16, 16),
]


# ---------------------------------------------------------------- colours
#
# Read from Rebrickable rather than written here: see lego_colours.py and the
# generator that produces it. The hand-written list this replaced held 43
# colours, filtered to what LEGO sells today so that a parts list was orderable.
# That constraint cost more than it bought — a sandstone facade has no good
# match in 43 colours — and it is the wrong constraint for a model as likely to
# be printed as bought, since a colour retired in 2010 prints exactly as well as
# one in this year's sets.
from app.services.lego_colours import SOLID as COLOURS
from app.services.lego_colours import TRANSPARENT as GLAZING
from app.services.lego_colours import Colour

# Glazing.
#
# A window at this scale is not a window part. The catalogue's window frames are
# two courses tall and a fixed four studs wide, so placing one means finding an
# opening of exactly that size and hoping the building agrees; and the moment one
# lands half a course out, the whole wall around it has to shift. What LEGO's own
# Architecture sets do instead is simpler and looks better: ordinary brick shapes
# in a transparent colour. The geometry is unchanged, every size in the brick
# table is available, and the result reads as glass because it *is* glass.
#
# Trans-Brown is the default because it is smoked glass, which is what a window
# in a photograph almost always is — a dark opening, not a clear one. Trans-Clear
# reads as a hole in the wall from most angles.


# The one used unless a caller says otherwise.
DEFAULT_GLAZING_ID = 40

COLOURS_BY_ID = {c.colour_id: c for c in COLOURS + GLAZING}

# What the hidden support columns are built from. One cheap, ubiquitous colour
# beats matching the surface: nobody sees it, and it keeps the shopping list short.
FILL_COLOUR_ID = 71  # Light Bluish Gray


def nearest_colour(rgb: tuple[int, int, int]) -> Colour:
    """Snap an arbitrary RGB value to the closest colour LEGO actually sells.

    Uses the "redmean" weighted distance, which tracks human colour perception
    far better than plain Euclidean RGB while needing no colour-space conversion.
    """
    r, g, b = rgb
    best = COLOURS[0]
    best_dist = float("inf")
    for colour in COLOURS:
        cr, cg, cb = colour.rgb
        rmean = (r + cr) / 2
        dr, dg, db = r - cr, g - cg, b - cb
        dist = (
            (2 + rmean / 256) * dr * dr
            + 4 * dg * dg
            + (2 + (255 - rmean) / 256) * db * db
        )
        if dist < best_dist:
            best_dist = dist
            best = colour
    return best


def choose_baseplate(grid_w: int, grid_h: int) -> dict[str, object]:
    """Pick the baseplate arrangement that covers the build area."""
    for part_num, name, bw, bh in BASEPLATES:
        if grid_w <= bw and grid_h <= bh:
            return {"partId": part_num, "name": name, "quantity": 1}
    # Larger than a single 32x32 — tile them.
    part_num, name, bw, bh = BASEPLATES[0]
    across = -(-grid_w // bw)
    down = -(-grid_h // bh)
    return {"partId": part_num, "name": name, "quantity": across * down}
